### ISSUE TITLE
Option for multiple environments?

### ISSUE THREAD

**Issue by arcreative** [gunpowderlabs/gulp-environments#10]
I would love to have the ability to do an inline check for `production` or `staging` in my gulp tasks, maybe something like the following:

```
...
    .pipe(environments.in(['production', 'staging'], uglify()))
...or...
    .pipe(environments.not(['production', 'staging'], uglify()))
...
```

Is there currently a supported way of doing this?

**Comment by ryanaltvater** [comment]
@arcreative Any update on this (or another solution)? I'm in need of the same thing.

**Comment by arcreative** [comment]
@ryanaltvater I did indeed create an alternative for this: https://github.com/arcreative/gulp-if-env

My apologies if that's not what you were needing, it's been a while since I've dealt with gulp :-)

**Comment by arcreative** [comment]
https://www.npmjs.com/package/gulp-if-env

**Comment by ryanaltvater** [comment]
@arcreative Awesome, thank you! I'll check it out right after lunch and get back to you with any feedback. :)

**Comment by ryanaltvater** [comment]
@arcreative Sorry for the late response. Your solution worked well and really helped. Does exactly what I need it to do, and didn't run into any issues. 👍 Thanks a bunch!

**Comment by arcreative** [comment]
@ryanaltvater Glad to hear it, thanks for getting back!
