### ISSUE TITLE
Conditional compiling (if-else)?

### ISSUE THREAD

**Issue by ghost** [gunpowderlabs/gulp-environments#11]
I have files that are supposed to be compiled to `temp` folder if the `NODE_ENV` value is `development`; otherwise, to `app` folder.

I've tried these 4 ways but all failed:

``` javascript
// the $ sign is gulpLoadPlugins()
const isDev = $.environments.development;
const isProd = $.environments.production;
```

1. As what the docs instructed
`.pipe(isDev() ? gulp.dest('temp') : gulp.dest('app'))`

2. With `gulp-if`
`.pipe($.if(isDev(), gulp.dest('temp'), gulp.dest('app')))`

3. Processing the condition inside the `gulp.dest()` method
`.pipe(gulp.dest(isDev() ? 'temp' : 'app'))`

4. Both condition piped
`.pipe(isDev(gulp.dest('temp')))`
`.pipe(isProd(gulp.dest('app')))`

THE RESULT:
Both `NODE_ENV` values compile files to the same folder.

Removing the parentheses after `isDev` doesn't solve the problem either.

**Comment by psyho** [comment]
Have you tried setting the environment with  `--env` instead of the NODE_ENV variable? It looks like the problem might be not in how you are using `isDev` and `isProd` but with how the environment is set.

**Comment by ghost** [comment]
@psyho [SOLVED] Thanks :smiley:  I had no idea there's a `--env` flag in its CLI until I read the documentation of `gulp-environment`. I'm a Gulp 4 user, by the way.
