### ISSUE TITLE
Trouble setting custom environments / checking active environment

### ISSUE THREAD

**Issue by skeddles** [gunpowderlabs/gulp-environments#15]
I wanted to create 2 environments, based on my process.env.HOST variable, which should be either "live" or "dev".

```
var environments = require('gulp-environments');
var liveOnly = environments.make('live');
var devOnly = environments.make('dev');
environments.current(process.env.HOST);
console.log(liveOnly?true:false,devOnly?true:false)
```

This is on my dev environment, and I know process.env.HOST resolves to "dev". But in the above example, the console logs `true true`, which according to your docs indicates that both environments are active? Maybe I'm misunderstanding what "active" means, but I took it to mean it's set as the current task.

Also if I use `console.log(liveOnly(),devOnly())` i instead get `false false`, not sure what that's about.

**Comment by skeddles** [comment]
I see what I did wrong now, using liveOnly instead of liveOnly() in the comparison, and passing a string to the .current() instead of an environment. 

I guess you can change this to a suggestion to allow passing a string identifier to .current(), which seems like it would be a pretty common use case, plus throwing an error when you try to set a current environment that doesn't exist.

**Comment by wrozka** [comment]
`gulp-environments` sets the environment based `NODE_ENV`, `--env` param or option set in `current` function. Details of this behaviour are described in [README](
https://github.com/gunpowderlabs/gulp-environments#setting-the-environment).

You need to call the environment function to see whether it is the current one (`liveOnly() => true / false`)

I'm closing this one, but feel free to reopen it if you have any questions.

**Comment by skeddles** [comment]
I know, but I don't use the NODE_ENV parameter, I use my own HOST parameter so I end up having to set it myself, which is what led to this.

**Comment by wrozka** [comment]
Oh, I see now, thanks for the clarification! I don't have time to work on new features now, but feel free to post a PR!
